example:
  property: "I AM IN THE DEFAULT HELLO"
spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      platform: mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eagle_eye_local
    username: root
    password:
    dbcp2:
      test-while-idle: true
      validation-query: "SELECT 1"
